### ISSUE TITLE
RTD build still not working

### ISSUE THREAD

**Issue by ayshih** [foxsi/foxsi-smex#16]
The reason that Read the Docs (RTD) documentation is still not building even after #15 is because it doesn't know to install `numpydoc`.  The repo needs a `requirements.txt` file (or equivalent) that includes `numpydoc`, and the RTD configuration needs to point to that same file.  (Alternatively, one could add `numpydoc` to `setup.py` as a requirement, but the average user will have no reason to install `numpydoc`.)

**Comment by ayshih** [comment]
Now the problem seems to be due to matplotlib not installing correctly due to missing freetype and png libraries.

For the record, the documentation is here: http://foxsi-smex.readthedocs.org/en/latest/

**Comment by ehsteve** [comment]
Building now.
