### ISSUE TITLE
Add capability to correctly deal with discretization when convolving the PSF.

### ISSUE THREAD

**Issue by ehsteve** [foxsi/foxsi-smex#23]
This is implemented on python side in astropy. See this [page](http://docs.astropy.org/en/stable/convolution/kernels.html#discretization).

**Comment by ayshih** [comment]
Already done.

On both the Python and IDL sides, the PSF function accepts the keyword argument `oversample` and the convolving function accepts the keyword argument `oversample_psf`.  An integer greater than 1 specifies the number of subpixels to sample within each pixel, and then the average is used for the value of the PSF in that pixel.  This approach is not as accurate as the much slower numerical integration, but it's "good enough".  A value of 3 is quite usable, with a good balance between accuracy and performance, and could be considered as a default.
